CONTIKI = /opt/contiki
#CONTIKI = /home/erik/skola/wcnes/contiki

all: meshtest meshtestsink netfloodtest netfloodtestsink phidgetstest rssitest

CFLAGS += -DPROJECT_CONF_H=1

include $(CONTIKI)/Makefile.include

