CONTIKI_PROJECT = sink
CONTIKI = /opt/contiki
#CONTIKI = /home/erik/skola/wcnes/contiki

CONTIKI_SOURCEFILES += callbacks.c
APPS = 

all: $(CONTIKI_PROJECT)

upload: $(CONTIKI_PROJECT).upload

include $(CONTIKI)/Makefile.include

